### ISSUE TITLE
.withServiceCallTransports(ServiceCallTransport.Grpc)

### ISSUE THREAD

**Issue by alexknips** [lagom/grpc-sbt-experiments#7]
How did you make `.withServiceCallTransports(ServiceCallTransport.Grpc)` work?
I cannot find either the function or the namespace 

`com.lightbend.lagom.scaladsl.api.ServiceCallTransport`

Did you use a custom Lagom build?

**Comment by ignasi35** [comment]
Hi @alexknips this was an experiment based on a (now obsolete) branch of https://github.com/lagom/lagom .

I'll actually archive this repo to further avoid confusion.
